### PR TITLE
tests pass, ship it!

### PR DESCRIPTION
**Pull request by jjl**
Oh my god this took waaaay longer than I thought it would and I never want to do date/time manipulation ever again.

For bonus, I threw in hstore support, but hstore support in jdbc is shit, it maps it to a hashmap of string.

### CODE REVIEW

**Comment by jjl** [comment]
solves issue #3

**Comment by JuneKelly** [comment]
At a first glance, this looks good.

My plan:
- review the changes
- merge this pull-request
- rename this repo to `mpg`
- publish a new artifact to clojars called `mpg`

**Comment by JuneKelly** [comment]
I'm hitting two failing tests locally after the merge:

(with Postgres 9.5)

```
$ lein test

lein test mpg.core-test

lein test :only mpg.core-test/datetime

FAIL in (datetime) (core_test.clj:71)
ZonedDateTime roundtrips through timestamp/tz
expected: (= v (roundtrip-unprepared "timestamp" v) (roundtrip-prepared "timestamp" v))
  actual: (not (= #object[java.time.ZonedDateTime 0x325bb9a6 "2016-04-25T13:30:08.493Z[UTC]"] #object[java.time.ZonedDateTime 0x1d12b024 "2016-04-25T12:30:08.493Z[UTC]"] #object[java.time.ZonedDateTime 0x72fe8a4f "2016-04-25T12:30:08.493Z[UTC]"]))

lein test :only mpg.core-test/datetime

FAIL in (datetime) (core_test.clj:74)
ZonedDateTime roundtrips through timestamp/tz
expected: (= v (roundtrip-unprepared "timestamptz" v) (roundtrip-prepared "timestamptz" v))
  actual: (not (= #object[java.time.ZonedDateTime 0x325bb9a6 "2016-04-25T13:30:08.493Z[UTC]"] #object[java.time.ZonedDateTime 0x43effd89 "2016-04-25T12:30:08.493Z[UTC]"] #object[java.time.ZonedDateTime 0x2c16fadb "2016-04-25T12:30:08.493Z[UTC]"]))

Ran 3 tests containing 7 assertions.
2 failures, 0 errors.
Tests failed.
```

**Comment by jjl** [comment]
o_O

I've just checked out your branch and run the tests and it passes _absolutely fine_. FreeBSD/OpenJDK8/Postgres 9.5

**Comment by jjl** [comment]
Is your postgres configured to a timezone other than UTC?

**Comment by JuneKelly** [comment]
The timezone was set to "GB" in `postgresql.conf`. I changed it to "UTC", restarted postgres and got the same result.

I'll try setting up on a new vm and see if it's just my machine being funny.

**Comment by jjl** [comment]
Hrm. Can you try changing the query to `select (current_timestamp at time zone "UTC") :: timestamptz as result` and seeing if that fixes it?

**Comment by jjl** [comment]
I've managed to reproduce. The problem isn't postgres, it's java! Exporting TZ=Europe/Amsterdam into the environment causes it to reliably be off by two hours (well, until clocks-back anyway...). Now that I can reproduce, I can work up a patch :)

**Comment by jjl** [comment]
Okay, not that github seems to have noticed now it's marked merged, but i've fixed it. Turns out that java.sql.Timestamp/valueOf expects timestamps to be in the system default timezone, not in UTC.

Add to all of this the inconsistent treatment of the 'user.timezone' system property (some things pay attention if you change it mid run, others don't) and all-in-all, i'm bored of timezones now :)

**Comment by JuneKelly** [comment]
Awesome, could you open another pull-request with the latest change? :)

**Pull request merged**
